# Generated by Erlang.mk. Edit at your own risk!

src/rabbit_compression.erl:: /mnt/c/repos/rabbitmq-management-decompression/deps/rabbitmq_management_agent/include/rabbit_mgmt_records.hrl; @touch $@

COMPILE_FIRST +=
